//
// File generated by d:\extlibraries\root\3.00.06\bin\rootcint at Mon Aug 20 18:43:46 2001.
// Do NOT change. Changes will be lost next time file is generated
//
#include "mcRootDataCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, RMcParticle *&obj)
{
   // Read a pointer to an object of class RMcParticle.

   obj = (RMcParticle *) buf.ReadObject(RMcParticle::Class());
   return buf;
}

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, RMcVertex *&obj)
{
   // Read a pointer to an object of class RMcVertex.

   obj = (RMcVertex *) buf.ReadObject(RMcVertex::Class());
   return buf;
}

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, RMcEvent *&obj)
{
   // Read a pointer to an object of class RMcEvent.

   obj = (RMcEvent *) buf.ReadObject(RMcEvent::Class());
   return buf;
}

//______________________________________________________________________________
void RMcVertex::Streamer(TBuffer &R__b)
{
   // Stream an object of class RMcVertex.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_pMomI;
      R__b >> m_pMomF;
      R__b >> m_pPosI;
      R__b >> m_pPosF;
      R__b >> m_timeOfFlight;
      R__b >> m_mcDaugterParticles;
      R__b >> m_motherParticle;
      R__b >> m_mainParticle;
      R__b.CheckByteCount(R__s, R__c, RMcVertex::IsA());
   } else {
      R__c = R__b.WriteVersion(RMcVertex::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_pMomI;
      R__b << m_pMomF;
      R__b << m_pPosI;
      R__b << m_pPosF;
      R__b << m_timeOfFlight;
      R__b << m_mcDaugterParticles;
      R__b << m_motherParticle;
      R__b << m_mainParticle;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void RMcVertex::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class RMcVertex.

   TClass *R__cl  = RMcVertex::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "*m_pMomI", &m_pMomI);
   R__insp.Inspect(R__cl, R__parent, "*m_pMomF", &m_pMomF);
   R__insp.Inspect(R__cl, R__parent, "*m_pPosI", &m_pPosI);
   R__insp.Inspect(R__cl, R__parent, "*m_pPosF", &m_pPosF);
   R__insp.Inspect(R__cl, R__parent, "m_timeOfFlight", &m_timeOfFlight);
   R__insp.Inspect(R__cl, R__parent, "*m_mcDaugterParticles", &m_mcDaugterParticles);
   R__insp.Inspect(R__cl, R__parent, "*m_motherParticle", &m_motherParticle);
   R__insp.Inspect(R__cl, R__parent, "*m_mainParticle", &m_mainParticle);
   TObject::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *RMcVertex::Class_Name()
{
   // Return the class name for RMcVertex.
   return "RMcVertex";
}

// Static variable to hold initialization object
static RMcVertex::R__Init __gR__InitRMcVertex(0);

//______________________________________________________________________________
void RMcParticle::Streamer(TBuffer &R__b)
{
   // Stream an object of class RMcParticle.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_nPDGId;
      R__b >> m_mcVertex;
      R__b.CheckByteCount(R__s, R__c, RMcParticle::IsA());
   } else {
      R__c = R__b.WriteVersion(RMcParticle::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_nPDGId;
      R__b << m_mcVertex;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void RMcParticle::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class RMcParticle.

   TClass *R__cl  = RMcParticle::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "m_nPDGId", &m_nPDGId);
   R__insp.Inspect(R__cl, R__parent, "*m_mcVertex", &m_mcVertex);
   TObject::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *RMcParticle::Class_Name()
{
   // Return the class name for RMcParticle.
   return "RMcParticle";
}

// Static variable to hold initialization object
static RMcParticle::R__Init __gR__InitRMcParticle(0);

//______________________________________________________________________________
void RMcEvent::Streamer(TBuffer &R__b)
{
   // Stream an object of class RMcEvent.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_nEvent;
      R__b >> m_nRun;
      R__b >> m_pVertList;
      R__b >> m_nVertCount;
      R__b.CheckByteCount(R__s, R__c, RMcEvent::IsA());
   } else {
      R__c = R__b.WriteVersion(RMcEvent::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_nEvent;
      R__b << m_nRun;
      R__b << m_pVertList;
      R__b << m_nVertCount;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void RMcEvent::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class RMcEvent.

   TClass *R__cl  = RMcEvent::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "m_nEvent", &m_nEvent);
   R__insp.Inspect(R__cl, R__parent, "m_nRun", &m_nRun);
   R__insp.Inspect(R__cl, R__parent, "*m_pVertList", &m_pVertList);
   R__insp.Inspect(R__cl, R__parent, "m_nVertCount", &m_nVertCount);
   TObject::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *RMcEvent::Class_Name()
{
   // Return the class name for RMcEvent.
   return "RMcEvent";
}

// Static variable to hold initialization object
static RMcEvent::R__Init __gR__InitRMcEvent(0);

/********************************************************
* mcRootDataCint.cxx
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablemcRootDataCint();

extern "C" void G__set_cpp_environmentmcRootDataCint() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("RMcVertex.h");
  G__add_compiledheader("RMcParticle.h");
  G__add_compiledheader("RMcEvent.h");
  G__cpp_reset_tagtablemcRootDataCint();
}
class G__mcRootDataCintdOcxx_tag {};

void* operator new(size_t size,G__mcRootDataCintdOcxx_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__mcRootDataCintdOcxx_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_mcRootDataCintdOcxx() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevmcRootDataCint() { return(30051472); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* RMcParticle */
static int G__RMcParticle_RMcParticle_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   RMcParticle *p=NULL;
   if(G__getaryconstruct()) p=new RMcParticle[G__getaryconstruct()];
   else                    p=new RMcParticle;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_RMcParticle_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   RMcParticle *p=NULL;
      p = new RMcParticle((Int_t)G__int(libp->para[0]),(RMcVertex*)G__int(libp->para[1]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_getPDGId_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const RMcParticle*)(G__getstructoffset()))->getPDGId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_mcVertex_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcParticle*)(G__getstructoffset()))->mcVertex());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_setMcVertex_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcParticle*)(G__getstructoffset()))->setMcVertex((RMcVertex*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_Class_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcParticle*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_Class_Name_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcParticle*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_Class_Version_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((RMcParticle*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_Dictionary_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcParticle*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_IsA_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcParticle*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_ShowMembers_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcParticle*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_Streamer_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcParticle*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_StreamerNVirtual_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcParticle*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_DeclFileName_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcParticle*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_DeclFileLine_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcParticle*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_ImplFileName_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcParticle*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcParticle_ImplFileLine_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcParticle*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RMcParticle_RMcParticle_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   RMcParticle *p;
   p=new RMcParticle(*(RMcParticle*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RMcParticle G__TRMcParticle;
static int G__RMcParticle_wARMcParticle_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (RMcParticle *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (RMcParticle *)((G__getstructoffset())+sizeof(RMcParticle)*i);
   else  delete (RMcParticle *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* RMcVertex */
static int G__RMcVertex_RMcVertex_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   RMcVertex *p=NULL;
   if(G__getaryconstruct()) p=new RMcVertex[G__getaryconstruct()];
   else                    p=new RMcVertex;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_RMcVertex_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   RMcVertex *p=NULL;
      p = new RMcVertex(
(TLorentzVector*)G__int(libp->para[0]),(TLorentzVector*)G__int(libp->para[1])
,(TLorentzVector*)G__int(libp->para[2]),(TLorentzVector*)G__int(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_getPosInitial_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->getPosInitial());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_getPosFinal_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->getPosFinal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_getMomInitial_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->getMomInitial());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_getMomFinal_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->getMomFinal());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setPosInitial_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setPosInitial((TLorentzVector*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setPosFinal_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setPosFinal((TLorentzVector*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setMomInitial_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setMomInitial((TLorentzVector*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setMomFinal_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setMomFinal((TLorentzVector*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_timeOfFlight_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((const RMcVertex*)(G__getstructoffset()))->timeOfFlight());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setTimeOfFlight_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setTimeOfFlight((double)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_mcParticle_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcVertex*)(G__getstructoffset()))->mcParticle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setMcParticle_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setMcParticle((RMcParticle*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_motherMcParticle_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcVertex*)(G__getstructoffset()))->motherMcParticle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_setMotherMcParticle_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->setMotherMcParticle((RMcParticle*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_daughterMcParticles_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->daughterMcParticles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_addDaughterMcParticle_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->addDaughterMcParticle((RMcParticle*)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_Class_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcVertex*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_Class_Name_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcVertex*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_Class_Version_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((RMcVertex*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_Dictionary_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_IsA_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcVertex*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_ShowMembers_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_Streamer_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_StreamerNVirtual_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcVertex*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_DeclFileName_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcVertex*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_DeclFileLine_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcVertex*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_ImplFileName_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcVertex*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcVertex_ImplFileLine_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcVertex*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RMcVertex_RMcVertex_1_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   RMcVertex *p;
   p=new RMcVertex(*(RMcVertex*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RMcVertex G__TRMcVertex;
static int G__RMcVertex_wARMcVertex_2_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (RMcVertex *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (RMcVertex *)((G__getstructoffset())+sizeof(RMcVertex)*i);
   else  delete (RMcVertex *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* RMcEvent */
static int G__RMcEvent_RMcEvent_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   RMcEvent *p=NULL;
   if(G__getaryconstruct()) p=new RMcEvent[G__getaryconstruct()];
   else                    p=new RMcEvent;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Clean_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->Clean();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Create_3_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->Create();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_getEvent_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const RMcEvent*)(G__getstructoffset()))->getEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_getRun_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const RMcEvent*)(G__getstructoffset()))->getRun());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_getVertCount_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((const RMcEvent*)(G__getstructoffset()))->getVertCount());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_setEvent_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->setEvent((Int_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_setRun_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->setRun((Int_t)G__int(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_getVert_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcEvent*)(G__getstructoffset()))->getVert((Int_t)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_addVert_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcEvent*)(G__getstructoffset()))->addVert((RMcVertex*)G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Class_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((RMcEvent*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Class_Name_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcEvent*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Class_Version_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((RMcEvent*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Dictionary_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_IsA_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const RMcEvent*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_ShowMembers_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_Streamer_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_StreamerNVirtual_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((RMcEvent*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_DeclFileName_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcEvent*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_DeclFileLine_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcEvent*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_ImplFileName_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((RMcEvent*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__RMcEvent_ImplFileLine_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((RMcEvent*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__RMcEvent_RMcEvent_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   RMcEvent *p;
   p=new RMcEvent(*(RMcEvent*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef RMcEvent G__TRMcEvent;
static int G__RMcEvent_wARMcEvent_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (RMcEvent *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (RMcEvent *)((G__getstructoffset())+sizeof(RMcEvent)*i);
   else  delete (RMcEvent *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* RMcParticle */

/* RMcVertex */

/* RMcEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmcRootDataCint {
 public:
  G__Sizep2memfuncmcRootDataCint() {p=&G__Sizep2memfuncmcRootDataCint::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmcRootDataCint::*p)();
};

size_t G__get_sizep2memfuncmcRootDataCint()
{
  G__Sizep2memfuncmcRootDataCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemcRootDataCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle))) {
     RMcParticle *G__Lderived;
     G__Lderived=(RMcParticle*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),G__get_linked_tagnum(&G__mcRootDataCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex))) {
     RMcVertex *G__Lderived;
     G__Lderived=(RMcVertex*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),G__get_linked_tagnum(&G__mcRootDataCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent))) {
     RMcEvent *G__Lderived;
     G__Lderived=(RMcEvent*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent),G__get_linked_tagnum(&G__mcRootDataCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemcRootDataCint() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte",0);
   G__search_typename2("UChar_t",98,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Character 1 byte",0);
   G__search_typename2("Short_t",115,-1,0,
-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes",0);
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes",0);
   G__search_typename2("Seek_t",105,-1,0,
-1);
   G__setnewtype(-1,"File pointer",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 4 bytes",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Float 8 bytes",0);
   G__search_typename2("Text_t",99,-1,0,
-1);
   G__setnewtype(-1,"General string",0);
   G__search_typename2("Bool_t",98,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true)",0);
   G__search_typename2("Byte_t",98,-1,0,
-1);
   G__setnewtype(-1,"Byte (8 bits)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier",0);
   G__search_typename2("Option_t",99,-1,0,
-1);
   G__setnewtype(-1,"Option string",0);
   G__search_typename2("Ssiz_t",105,-1,0,
-1);
   G__setnewtype(-1,"String size",0);
   G__search_typename2("Real_t",102,-1,0,
-1);
   G__setnewtype(-1,"TVector and TMatrix element type",0);
   G__search_typename2("Streamer_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VoidFuncPtr_t",89,-1,0,
-1);
   G__setnewtype(-1,"pointer to void function",0);
   G__search_typename2("FreeHookFun_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocCFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Axis_t",100,-1,0,
-1);
   G__setnewtype(-1,"Axis values type",0);
   G__search_typename2("Stat_t",100,-1,0,
-1);
   G__setnewtype(-1,"Statistics type",0);
   G__search_typename2("ErrorHandlerFunc_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* RMcParticle */
static void G__setup_memvarRMcParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle));
   { RMcParticle *p; p=(RMcParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_nPDGId=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,-1,4,"m_mcVertex=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* RMcVertex */
static void G__setup_memvarRMcVertex(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex));
   { RMcVertex *p; p=(RMcVertex*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pMomI=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pMomF=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pPosI=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pPosF=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"m_timeOfFlight=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TObjArray),-1,-1,4,"m_mcDaugterParticles=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,-1,4,"m_motherParticle=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,-1,4,"m_mainParticle=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* RMcEvent */
static void G__setup_memvarRMcEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent));
   { RMcEvent *p; p=(RMcEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_nEvent=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_nRun=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TObjArray),-1,-1,4,"m_pVertList=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_nVertCount=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmcRootDataCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncRMcParticle(void) {
   /* RMcParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle));
   G__memfunc_setup("RMcParticle",1078,G__RMcParticle_RMcParticle_0_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RMcParticle",1078,G__RMcParticle_RMcParticle_1_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,0,2,1,1,0,
"i - 'Int_t' 0 - id U 'RMcVertex' - 0 - pVertex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPDGId",712,G__RMcParticle_getPDGId_3_0,105,-1,G__defined_typename("Int_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("mcVertex",846,G__RMcParticle_mcVertex_4_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMcVertex",1146,G__RMcParticle_setMcVertex_5_0,121,-1,-1,0,1,1,1,0,"U 'RMcVertex' - 0 - value",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__RMcParticle_Class_6_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__RMcParticle_Class_Name_7_0,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__RMcParticle_Class_Version_8_0,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__RMcParticle_Dictionary_9_0,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__RMcParticle_IsA_0_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__RMcParticle_ShowMembers_1_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__RMcParticle_Streamer_2_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RMcParticle_StreamerNVirtual_3_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__RMcParticle_DeclFileName_4_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__RMcParticle_DeclFileLine_5_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__RMcParticle_ImplFileName_6_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__RMcParticle_ImplFileLine_7_1,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("RMcParticle",1078,G__RMcParticle_RMcParticle_8_1,(int)('i'),G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,0,1,1,1,0,"u 'RMcParticle' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~RMcParticle",1204,G__RMcParticle_wARMcParticle_9_1,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncRMcVertex(void) {
   /* RMcVertex */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex));
   G__memfunc_setup("RMcVertex",896,G__RMcVertex_RMcVertex_0_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("RMcVertex",896,G__RMcVertex_RMcVertex_1_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,0,4,1,1,0,
"U 'TLorentzVector' - 0 - pPosI U 'TLorentzVector' - 0 - pPosF "
"U 'TLorentzVector' - 0 - pMomI U 'TLorentzVector' - 0 - pMomF",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosInitial",1340,G__RMcVertex_getPosInitial_3_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosFinal",1116,G__RMcVertex_getPosFinal_4_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomInitial",1331,G__RMcVertex_getMomInitial_5_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomFinal",1107,G__RMcVertex_getMomFinal_6_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPosInitial",1352,G__RMcVertex_setPosInitial_7_0,121,-1,-1,0,1,1,1,0,"U 'TLorentzVector' - 0 - pPosI",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPosFinal",1128,G__RMcVertex_setPosFinal_8_0,121,-1,-1,0,1,1,1,0,"U 'TLorentzVector' - 0 - pPosF",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMomInitial",1343,G__RMcVertex_setMomInitial_9_0,121,-1,-1,0,1,1,1,0,"U 'TLorentzVector' - 0 - pMomI",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMomFinal",1119,G__RMcVertex_setMomFinal_0_1,121,-1,-1,0,1,1,1,0,"U 'TLorentzVector' - 0 - pMomF",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("timeOfFlight",1218,G__RMcVertex_timeOfFlight_1_1,100,-1,G__defined_typename("Double_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setTimeOfFlight",1518,G__RMcVertex_setTimeOfFlight_2_1,121,-1,-1,0,1,1,1,0,"d - - 0 - value",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("mcParticle",1028,G__RMcVertex_mcParticle_3_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMcParticle",1328,G__RMcVertex_setMcParticle_4_1,121,-1,-1,0,1,1,1,0,"U 'RMcParticle' - 0 - value",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("motherMcParticle",1651,G__RMcVertex_motherMcParticle_5_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMotherMcParticle",1951,G__RMcVertex_setMotherMcParticle_6_1,121,-1,-1,0,1,1,1,0,"U 'RMcParticle' - 0 - value",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("daughterMcParticles",1963,G__RMcVertex_daughterMcParticles_7_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TObjArray),-1,0,0,1,1,9,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addDaughterMcParticle",2113,G__RMcVertex_addDaughterMcParticle_8_1,121,-1,-1,0,1,1,1,0,"U 'RMcParticle' - 0 - particle",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__RMcVertex_Class_9_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__RMcVertex_Class_Name_0_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__RMcVertex_Class_Version_1_2,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__RMcVertex_Dictionary_2_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__RMcVertex_IsA_3_2,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__RMcVertex_ShowMembers_4_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__RMcVertex_Streamer_5_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RMcVertex_StreamerNVirtual_6_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__RMcVertex_DeclFileName_7_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__RMcVertex_DeclFileLine_8_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__RMcVertex_ImplFileName_9_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__RMcVertex_ImplFileLine_0_3,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("RMcVertex",896,G__RMcVertex_RMcVertex_1_3,(int)('i'),G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,0,1,1,1,0,"u 'RMcVertex' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~RMcVertex",1022,G__RMcVertex_wARMcVertex_2_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncRMcEvent(void) {
   /* RMcEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent));
   G__memfunc_setup("RMcEvent",772,G__RMcEvent_RMcEvent_0_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Clean",483,G__RMcEvent_Clean_2_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Create",596,G__RMcEvent_Create_3_0,121,-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getEvent",834,G__RMcEvent_getEvent_4_0,105,-1,G__defined_typename("Int_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getRun",629,G__RMcEvent_getRun_5_0,105,-1,G__defined_typename("Int_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getVertCount",1258,G__RMcEvent_getVertCount_6_0,105,-1,G__defined_typename("Int_t"),0,0,1,1,8,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setEvent",846,G__RMcEvent_setEvent_7_0,121,-1,-1,0,1,1,1,0,"i - 'Int_t' 0 - nEvent",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setRun",641,G__RMcEvent_setRun_8_0,121,-1,-1,0,1,1,1,0,"i - 'Int_t' 0 - nRun",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getVert",737,G__RMcEvent_getVert_9_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),-1,0,1,1,1,8,"i - 'Int_t' 0 - index",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("addVert",714,G__RMcEvent_addVert_0_1,105,-1,G__defined_typename("Int_t"),0,1,1,1,0,"U 'RMcVertex' - 0 - pPart",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__RMcEvent_Class_1_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__RMcEvent_Class_Name_2_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__RMcEvent_Class_Version_3_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__RMcEvent_Dictionary_4_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__RMcEvent_IsA_5_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__RMcEvent_ShowMembers_6_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__RMcEvent_Streamer_7_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__RMcEvent_StreamerNVirtual_8_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__RMcEvent_DeclFileName_9_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__RMcEvent_DeclFileLine_0_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__RMcEvent_ImplFileName_1_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__RMcEvent_ImplFileLine_2_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("RMcEvent",772,G__RMcEvent_RMcEvent_3_2,(int)('i'),G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent),-1,0,1,1,1,0,"u 'RMcEvent' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~RMcEvent",898,G__RMcEvent_wARMcEvent_4_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmcRootDataCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_globalmcRootDataCint() {

   /* Setting up global variables */
   G__resetplocal();


   G__resetglobalenv();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_funcmcRootDataCint() {
   G__lastifuncposition();


   G__resetifuncposition();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mcRootDataCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_RMcParticle = { "RMcParticle" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_RMcVertex = { "RMcVertex" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_RMcEvent = { "RMcEvent" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemcRootDataCint() {
  G__mcRootDataCintLN_TClass.tagnum = -1 ;
  G__mcRootDataCintLN_TObjArray.tagnum = -1 ;
  G__mcRootDataCintLN_TObject.tagnum = -1 ;
  G__mcRootDataCintLN_TLorentzVector.tagnum = -1 ;
  G__mcRootDataCintLN_RMcParticle.tagnum = -1 ;
  G__mcRootDataCintLN_RMcVertex.tagnum = -1 ;
  G__mcRootDataCintLN_RMcEvent.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemcRootDataCint() {

   /* Setting up class,struct,union tag entry */
   G__tagtable_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcParticle),sizeof(RMcParticle),-1,29952,(char*)NULL,G__setup_memvarRMcParticle,G__setup_memfuncRMcParticle);
   G__tagtable_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcVertex),sizeof(RMcVertex),-1,29952,(char*)NULL,G__setup_memvarRMcVertex,G__setup_memfuncRMcVertex);
   G__tagtable_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_RMcEvent),sizeof(RMcEvent),-1,29952,(char*)NULL,G__setup_memvarRMcEvent,G__setup_memfuncRMcEvent);
}
extern "C" void G__cpp_setupmcRootDataCint(void) {
  G__check_setup_version(30051472,"G__cpp_setupmcRootDataCint()");
  G__set_cpp_environmentmcRootDataCint();
  G__cpp_setup_tagtablemcRootDataCint();

  G__cpp_setup_inheritancemcRootDataCint();

  G__cpp_setup_typetablemcRootDataCint();

  G__cpp_setup_memvarmcRootDataCint();

  G__cpp_setup_memfuncmcRootDataCint();
  G__cpp_setup_globalmcRootDataCint();
  G__cpp_setup_funcmcRootDataCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmcRootDataCint();
  return;
}
class G__cpp_setup_initmcRootDataCint {
  public:
    G__cpp_setup_initmcRootDataCint() { G__add_setup_func("mcRootDataCint",(G__incsetup)(&G__cpp_setupmcRootDataCint)); }
   ~G__cpp_setup_initmcRootDataCint() { G__remove_setup_func("mcRootDataCint"); }
};
G__cpp_setup_initmcRootDataCint G__cpp_setup_initializermcRootDataCint;

