//
// File generated by c:\root\bin\rootcint at Wed May 16 10:10:35 2001.
// Do NOT change. Changes will be lost next time file is generated
//
#include "mcRootDataCint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, MCVertex *&obj)
{
   // Read a pointer to an object of class MCVertex.

   obj = (MCVertex *) buf.ReadObject(MCVertex::Class());
   return buf;
}

//______________________________________________________________________________
TBuffer &operator>>(TBuffer &buf, MCParticle *&obj)
{
   // Read a pointer to an object of class MCParticle.

   obj = (MCParticle *) buf.ReadObject(MCParticle::Class());
   return buf;
}

//______________________________________________________________________________
void MCVertex::Streamer(TBuffer &R__b)
{
   // Stream an object of class MCVertex.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_pPos;
      R__b.CheckByteCount(R__s, R__c, MCVertex::IsA());
   } else {
      R__c = R__b.WriteVersion(MCVertex::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_pPos;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void MCVertex::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class MCVertex.

   TClass *R__cl  = MCVertex::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "*m_pPos", &m_pPos);
   TObject::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *MCVertex::Class_Name()
{
   // Return the class name for MCVertex.
   return "MCVertex";
}

// Static variable to hold initialization object
static MCVertex::R__Init __gR__InitMCVertex(0);

//______________________________________________________________________________
void MCParticle::Streamer(TBuffer &R__b)
{
   // Stream an object of class MCParticle.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> m_pMom;
      R__b >> m_nPDGId;
      R__b >> m_pVert;
      R__b >> m_pParent;
      R__b.CheckByteCount(R__s, R__c, MCParticle::IsA());
   } else {
      R__c = R__b.WriteVersion(MCParticle::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << m_pMom;
      R__b << m_nPDGId;
      R__b << m_pVert;
      R__b << m_pParent;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void MCParticle::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
   // Inspect the data members of an object of class MCParticle.

   TClass *R__cl  = MCParticle::IsA();
   Int_t   R__ncp = strlen(R__parent);
   if (R__ncp || R__cl || R__insp.IsA()) { }
   R__insp.Inspect(R__cl, R__parent, "*m_pMom", &m_pMom);
   R__insp.Inspect(R__cl, R__parent, "m_nPDGId", &m_nPDGId);
   R__insp.Inspect(R__cl, R__parent, "*m_pVert", &m_pVert);
   R__insp.Inspect(R__cl, R__parent, "*m_pParent", &m_pParent);
   TObject::ShowMembers(R__insp, R__parent);
}

//______________________________________________________________________________
const char *MCParticle::Class_Name()
{
   // Return the class name for MCParticle.
   return "MCParticle";
}

// Static variable to hold initialization object
static MCParticle::R__Init __gR__InitMCParticle(0);

/********************************************************
* mcRootDataCint.cxx
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

extern "C" void G__cpp_reset_tagtablemcRootDataCint();

extern "C" void G__set_cpp_environmentmcRootDataCint() {
  G__add_compiledheader("TROOT.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MCVertex.h");
  G__add_compiledheader("MCParticle.h");
  G__cpp_reset_tagtablemcRootDataCint();
}
class G__mcRootDataCintdOcxx_tag {};

void* operator new(size_t size,G__mcRootDataCintdOcxx_tag* p) {
  if(p && G__PVOID!=G__getgvp()) return((void*)p);
#ifndef G__ROOT
  return(malloc(size));
#else
  return(::operator new(size));
#endif
}

/* dummy, for exception */
#ifdef G__EH_DUMMY_DELETE
void operator delete(void *p,G__mcRootDataCintdOcxx_tag* x) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}
#endif

static void G__operator_delete(void *p) {
  if((long)p==G__getgvp() && G__PVOID!=G__getgvp()) return;
#ifndef G__ROOT
  free(p);
#else
  ::operator delete(p);
#endif
}

void G__DELDMY_mcRootDataCintdOcxx() { G__operator_delete(0); }

extern "C" int G__cpp_dllrevmcRootDataCint() { return(30051472); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MCVertex */
static int G__MCVertex_MCVertex_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCVertex *p=NULL;
   if(G__getaryconstruct()) p=new MCVertex[G__getaryconstruct()];
   else                    p=new MCVertex;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_MCVertex_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCVertex *p=NULL;
      p = new MCVertex((TLorentzVector*)G__int(libp->para[0]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_MCVertex_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCVertex *p=NULL;
      p = new MCVertex(
(Double_t)G__double(libp->para[0]),(Double_t)G__double(libp->para[1])
,(Double_t)G__double(libp->para[2]),(Double_t)G__double(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_getPosX_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCVertex*)(G__getstructoffset()))->getPosX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_getPosY_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCVertex*)(G__getstructoffset()))->getPosY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_getPosZ_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCVertex*)(G__getstructoffset()))->getPosZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_getTime_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCVertex*)(G__getstructoffset()))->getTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_getPosLV_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCVertex*)(G__getstructoffset()))->getPosLV());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_setPosX_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->setPosX((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_setPosY_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->setPosY((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_setPosZ_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->setPosZ((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_setTime_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->setTime((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_Class_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCVertex*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_Class_Name_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCVertex*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_Class_Version_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((MCVertex*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_Dictionary_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_IsA_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const MCVertex*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_ShowMembers_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_Streamer_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_StreamerNVirtual_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCVertex*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_DeclFileName_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCVertex*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_DeclFileLine_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((MCVertex*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_ImplFileName_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCVertex*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCVertex_ImplFileLine_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((MCVertex*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MCVertex_MCVertex_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   MCVertex *p;
   p=new MCVertex(*(MCVertex*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MCVertex G__TMCVertex;
static int G__MCVertex_wAMCVertex_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (MCVertex *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (MCVertex *)((G__getstructoffset())+sizeof(MCVertex)*i);
   else  delete (MCVertex *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* MCParticle */
static int G__MCParticle_MCParticle_0_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCParticle *p=NULL;
   if(G__getaryconstruct()) p=new MCParticle[G__getaryconstruct()];
   else                    p=new MCParticle;
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_MCParticle_1_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCParticle *p=NULL;
      p = new MCParticle(
(TLorentzVector*)G__int(libp->para[0]),(Int_t)G__int(libp->para[1])
,(MCParticle*)G__int(libp->para[2]),(MCVertex*)G__int(libp->para[3]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_MCParticle_2_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   MCParticle *p=NULL;
      p = new MCParticle(
(Double_t)G__double(libp->para[0]),(Double_t)G__double(libp->para[1])
,(Double_t)G__double(libp->para[2]),(Double_t)G__double(libp->para[3])
,(Int_t)G__int(libp->para[4]),(MCParticle*)G__int(libp->para[5])
,(MCVertex*)G__int(libp->para[6]));
      result7->obj.i = (long)p;
      result7->ref = (long)p;
      result7->type = 'u';
      result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getMomX_4_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCParticle*)(G__getstructoffset()))->getMomX());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getMomY_5_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCParticle*)(G__getstructoffset()))->getMomY());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getMomZ_6_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCParticle*)(G__getstructoffset()))->getMomZ());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getMom_7_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCParticle*)(G__getstructoffset()))->getMom());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getEnergy_8_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letdouble(result7,100,(double)((MCParticle*)(G__getstructoffset()))->getEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getMomLV_9_0(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCParticle*)(G__getstructoffset()))->getMomLV());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getVertex_0_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCParticle*)(G__getstructoffset()))->getVertex());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getParent_1_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCParticle*)(G__getstructoffset()))->getParent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_getPDGId_2_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((MCParticle*)(G__getstructoffset()))->getPDGId());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_setMomX_3_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->setMomX((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_setMomY_4_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->setMomY((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_setMomZ_5_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->setMomZ((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_setEnergy_6_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->setEnergy((Double_t)G__double(libp->para[0]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_Class_7_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((MCParticle*)(G__getstructoffset()))->Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_Class_Name_8_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCParticle*)(G__getstructoffset()))->Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_Class_Version_9_1(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,115,(long)((MCParticle*)(G__getstructoffset()))->Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_Dictionary_0_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->Dictionary();
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_IsA_1_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,85,(long)((const MCParticle*)(G__getstructoffset()))->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_ShowMembers_2_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->ShowMembers(*(TMemberInspector*)libp->para[0].ref,(char*)G__int(libp->para[1]));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_Streamer_3_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->Streamer(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_StreamerNVirtual_4_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__setnull(result7);
      ((MCParticle*)(G__getstructoffset()))->StreamerNVirtual(*(TBuffer*)libp->para[0].ref);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_DeclFileName_5_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCParticle*)(G__getstructoffset()))->DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_DeclFileLine_6_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((MCParticle*)(G__getstructoffset()))->DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_ImplFileName_7_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,67,(long)((MCParticle*)(G__getstructoffset()))->ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MCParticle_ImplFileLine_8_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
      G__letint(result7,105,(long)((MCParticle*)(G__getstructoffset()))->ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MCParticle_MCParticle_9_2(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash)
{
   MCParticle *p;
   p=new MCParticle(*(MCParticle*)G__int(libp->para[0]));
   result7->obj.i = (long)p;
   result7->ref = (long)p;
   result7->type = 'u';
   result7->tagnum = G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MCParticle G__TMCParticle;
static int G__MCParticle_wAMCParticle_0_3(G__value *result7,G__CONST char *funcname,struct G__param *libp,int hash) {
   if(G__getaryconstruct())
     if(G__PVOID==G__getgvp())
       delete[] (MCParticle *)(G__getstructoffset());
     else
       for(int i=G__getaryconstruct()-1;i>=0;i--)
         delete (MCParticle *)((G__getstructoffset())+sizeof(MCParticle)*i);
   else  delete (MCParticle *)(G__getstructoffset());
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MCVertex */

/* MCParticle */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmcRootDataCint {
 public:
  G__Sizep2memfuncmcRootDataCint() {p=&G__Sizep2memfuncmcRootDataCint::sizep2memfunc;}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmcRootDataCint::*p)();
};

size_t G__get_sizep2memfuncmcRootDataCint()
{
  G__Sizep2memfuncmcRootDataCint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemcRootDataCint() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex))) {
     MCVertex *G__Lderived;
     G__Lderived=(MCVertex*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),G__get_linked_tagnum(&G__mcRootDataCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle))) {
     MCParticle *G__Lderived;
     G__Lderived=(MCParticle*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),G__get_linked_tagnum(&G__mcRootDataCintLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemcRootDataCint() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,
-1);
   G__setnewtype(-1,"Signed Character 1 byte",0);
   G__search_typename2("UChar_t",98,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Character 1 byte",0);
   G__search_typename2("Short_t",115,-1,0,
-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes",0);
   G__search_typename2("UShort_t",114,-1,0,
-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes",0);
   G__search_typename2("Int_t",105,-1,0,
-1);
   G__setnewtype(-1,"Signed integer 4 bytes",0);
   G__search_typename2("UInt_t",104,-1,0,
-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes",0);
   G__search_typename2("Seek_t",105,-1,0,
-1);
   G__setnewtype(-1,"File pointer",0);
   G__search_typename2("Long_t",108,-1,0,
-1);
   G__setnewtype(-1,"Signed long integer 4 bytes",0);
   G__search_typename2("ULong_t",107,-1,0,
-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes",0);
   G__search_typename2("Float_t",102,-1,0,
-1);
   G__setnewtype(-1,"Float 4 bytes",0);
   G__search_typename2("Double_t",100,-1,0,
-1);
   G__setnewtype(-1,"Float 8 bytes",0);
   G__search_typename2("Text_t",99,-1,0,
-1);
   G__setnewtype(-1,"General string",0);
   G__search_typename2("Bool_t",98,-1,0,
-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true)",0);
   G__search_typename2("Byte_t",98,-1,0,
-1);
   G__setnewtype(-1,"Byte (8 bits)",0);
   G__search_typename2("Version_t",115,-1,0,
-1);
   G__setnewtype(-1,"Class version identifier",0);
   G__search_typename2("Option_t",99,-1,0,
-1);
   G__setnewtype(-1,"Option string",0);
   G__search_typename2("Ssiz_t",105,-1,0,
-1);
   G__setnewtype(-1,"String size",0);
   G__search_typename2("Real_t",102,-1,0,
-1);
   G__setnewtype(-1,"TVector and TMatrix element type",0);
   G__search_typename2("Streamer_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("VoidFuncPtr_t",89,-1,0,
-1);
   G__setnewtype(-1,"pointer to void function",0);
   G__search_typename2("FreeHookFun_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ReAllocCFun_t",81,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("Axis_t",100,-1,0,
-1);
   G__setnewtype(-1,"Axis values type",0);
   G__search_typename2("Stat_t",100,-1,0,
-1);
   G__setnewtype(-1,"Statistics type",0);
   G__search_typename2("ErrorHandlerFunc_t",89,-1,0,
-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MCVertex */
static void G__setup_memvarMCVertex(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex));
   { MCVertex *p; p=(MCVertex*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pPos=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* MCParticle */
static void G__setup_memvarMCParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle));
   { MCParticle *p; p=(MCParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,-1,4,"m_pMom=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"m_nPDGId=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,-1,4,"m_pVert=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,-1,4,"m_pParent=",0,(char*)NULL);
   G__memvar_setup((void*)NULL,85,0,0,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmcRootDataCint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMCVertex(void) {
   /* MCVertex */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex));
   G__memfunc_setup("MCVertex",782,G__MCVertex_MCVertex_0_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MCVertex",782,G__MCVertex_MCVertex_1_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,0,1,1,1,0,"U 'TLorentzVector' - 0 - pos",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MCVertex",782,G__MCVertex_MCVertex_2_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,0,4,1,1,0,
"d - 'Double_t' 0 - posX d - 'Double_t' 0 - posY "
"d - 'Double_t' 0 - posZ d - 'Double_t' 0 - time",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosX",714,G__MCVertex_getPosX_4_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosY",715,G__MCVertex_getPosY_5_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosZ",716,G__MCVertex_getPosZ_6_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getTime",719,G__MCVertex_getTime_7_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPosLV",788,G__MCVertex_getPosLV_8_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPosX",726,G__MCVertex_setPosX_9_0,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - posX",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPosY",727,G__MCVertex_setPosY_0_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - posY",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setPosZ",728,G__MCVertex_setPosZ_1_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - posZ",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setTime",731,G__MCVertex_setTime_2_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - time",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__MCVertex_Class_3_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__MCVertex_Class_Name_4_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__MCVertex_Class_Version_5_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__MCVertex_Dictionary_6_1,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__MCVertex_IsA_7_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__MCVertex_ShowMembers_8_1,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__MCVertex_Streamer_9_1,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MCVertex_StreamerNVirtual_0_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__MCVertex_DeclFileName_1_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__MCVertex_DeclFileLine_2_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__MCVertex_ImplFileName_3_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__MCVertex_ImplFileLine_4_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("MCVertex",782,G__MCVertex_MCVertex_5_2,(int)('i'),G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,0,1,1,1,0,"u 'MCVertex' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~MCVertex",908,G__MCVertex_wAMCVertex_6_2,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncMCParticle(void) {
   /* MCParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle));
   G__memfunc_setup("MCParticle",964,G__MCParticle_MCParticle_0_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MCParticle",964,G__MCParticle_MCParticle_1_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,0,4,1,1,0,
"U 'TLorentzVector' - 0 - pMom i - 'Int_t' 0 - id "
"U 'MCParticle' - 0 - pParent U 'MCVertex' - 0 - pVertex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("MCParticle",964,G__MCParticle_MCParticle_2_0,105,G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,0,7,1,1,0,
"d - 'Double_t' 0 - momX d - 'Double_t' 0 - momY "
"d - 'Double_t' 0 - momZ d - 'Double_t' 0 - energy "
"i - 'Int_t' 0 - id U 'MCParticle' - 0 - pParent "
"U 'MCVertex' - 0 - pVertex",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomX",705,G__MCParticle_getMomX_4_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomY",706,G__MCParticle_getMomY_5_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomZ",707,G__MCParticle_getMomZ_6_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMom",617,G__MCParticle_getMom_7_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getEnergy",938,G__MCParticle_getEnergy_8_0,100,-1,G__defined_typename("Double_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getMomLV",779,G__MCParticle_getMomLV_9_0,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TLorentzVector),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getVertex",958,G__MCParticle_getVertex_0_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getParent",938,G__MCParticle_getParent_1_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("getPDGId",712,G__MCParticle_getPDGId_2_1,105,-1,G__defined_typename("Int_t"),0,0,1,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMomX",717,G__MCParticle_setMomX_3_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - momX",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMomY",718,G__MCParticle_setMomY_4_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - momY",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setMomZ",719,G__MCParticle_setMomZ_5_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - momZ",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("setEnergy",950,G__MCParticle_setEnergy_6_1,121,-1,-1,0,1,1,1,0,"d - 'Double_t' 0 - energy",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class",502,G__MCParticle_Class_7_1,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Name",982,G__MCParticle_Class_Name_8_1,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Class_Version",1339,G__MCParticle_Class_Version_9_1,115,-1,G__defined_typename("Version_t"),0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("Dictionary",1046,G__MCParticle_Dictionary_0_2,121,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("IsA",253,G__MCParticle_IsA_1_2,85,G__get_linked_tagnum(&G__mcRootDataCintLN_TClass),-1,0,0,1,1,8,"",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("ShowMembers",1132,G__MCParticle_ShowMembers_2_2,121,-1,-1,0,2,1,1,0,
"u 'TMemberInspector' - 1 - insp C - - 0 - parent",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("Streamer",835,G__MCParticle_Streamer_3_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,1);
   G__memfunc_setup("StreamerNVirtual",1656,G__MCParticle_StreamerNVirtual_4_2,121,-1,-1,0,1,1,1,0,"u 'TBuffer' - 1 - b",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileName",1145,G__MCParticle_DeclFileName_5_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("DeclFileLine",1152,G__MCParticle_DeclFileLine_6_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileName",1171,G__MCParticle_ImplFileName_7_2,67,-1,-1,0,0,3,1,1,"",(char*)NULL,(void*)NULL,0);
   G__memfunc_setup("ImplFileLine",1178,G__MCParticle_ImplFileLine_8_2,105,-1,-1,0,0,3,1,0,"",(char*)NULL,(void*)NULL,0);
   // automatic copy constructor
   G__memfunc_setup("MCParticle",964,G__MCParticle_MCParticle_9_2,(int)('i'),G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),-1,0,1,1,1,0,"u 'MCParticle' - 1 - -",(char*)NULL,(void*)NULL,0);
   // automatic destructor
   G__memfunc_setup("~MCParticle",1090,G__MCParticle_wAMCParticle_0_3,(int)('y'),-1,-1,0,0,1,1,0,"",(char*)NULL,(void*)NULL,1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmcRootDataCint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_globalmcRootDataCint() {

   /* Setting up global variables */
   G__resetplocal();


   G__resetglobalenv();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
extern "C" void G__cpp_setup_funcmcRootDataCint() {
   G__lastifuncposition();


   G__resetifuncposition();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mcRootDataCintLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_MCVertex = { "MCVertex" , 99 , -1 };
G__linked_taginfo G__mcRootDataCintLN_MCParticle = { "MCParticle" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemcRootDataCint() {
  G__mcRootDataCintLN_TClass.tagnum = -1 ;
  G__mcRootDataCintLN_TObject.tagnum = -1 ;
  G__mcRootDataCintLN_TLorentzVector.tagnum = -1 ;
  G__mcRootDataCintLN_MCVertex.tagnum = -1 ;
  G__mcRootDataCintLN_MCParticle.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemcRootDataCint() {

   /* Setting up class,struct,union tag entry */
   G__tagtable_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCVertex),sizeof(MCVertex),-1,29952,(char*)NULL,G__setup_memvarMCVertex,G__setup_memfuncMCVertex);
   G__tagtable_setup(G__get_linked_tagnum(&G__mcRootDataCintLN_MCParticle),sizeof(MCParticle),-1,29952,(char*)NULL,G__setup_memvarMCParticle,G__setup_memfuncMCParticle);
}
extern "C" void G__cpp_setupmcRootDataCint(void) {
  G__check_setup_version(30051472,"G__cpp_setupmcRootDataCint()");
  G__set_cpp_environmentmcRootDataCint();
  G__cpp_setup_tagtablemcRootDataCint();

  G__cpp_setup_inheritancemcRootDataCint();

  G__cpp_setup_typetablemcRootDataCint();

  G__cpp_setup_memvarmcRootDataCint();

  G__cpp_setup_memfuncmcRootDataCint();
  G__cpp_setup_globalmcRootDataCint();
  G__cpp_setup_funcmcRootDataCint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmcRootDataCint();
  return;
}
class G__cpp_setup_initmcRootDataCint {
  public:
    G__cpp_setup_initmcRootDataCint() { G__add_setup_func("mcRootDataCint",(G__incsetup)(&G__cpp_setupmcRootDataCint)); }
   ~G__cpp_setup_initmcRootDataCint() { G__remove_setup_func("mcRootDataCint"); }
};
G__cpp_setup_initmcRootDataCint G__cpp_setup_initializermcRootDataCint;

